version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MONGO_HOST=mongo
    restart: always

  project:
    build:
      context: .
      dockerfile: Dockerfile.project
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MONGO_HOST=mongo
    restart: always

volumes:
  mongo_data:
